# Selecting and Inspecting Tabular Data

So far we've shown how to import and view CSV data. How can we actually interrogate and work with these files? 

**More specifically, how to use tabular data for text analysis?**



To do this we need to cover three steps:
- **Selecting** data (column and row-wise): what parts of the dataframe are relevant to your research?
- **Manipulating text columns**: converting text to numbers
- **Aggregating data**: analysing trends over time or language use across different groups


# 1 Data Selection

- Research often requires **data selection** (or sampling). What information is relevant to your research (e.g. a historical period)?
- Selection criteria based on **content** and/or **metadata**.
- In this example `names` are the **content**, and `year` and `gender` are **metadata**.

Selecting data from lists and dictionaries:

- retrieving values by position:
```python 
l = ['a','b']
l[1]
```
- retrieving values by key:
```python 
d = {'a': 1}
d['a']
```

Dataframes provide more powerful and advanced tools for selecting data compared to those that come with lists or dictionaries.

More technically, a `DataFrame` is a **two-dimensional array** of **indexed data** (which means that you to access content by row **and/or** column).

The code below shows the row and column index.

In [13]:
%%bash
# we need to unzip the file first
# run this cell before continuing
# we need to unzip a larger csv file with name data
mkdir data
wget -O data/names.zip https://github.com/Living-with-machines/dhoxss-text2tech/raw/dev/Sessions/data/names.zip
unzip -o data/names.zip -d data # unzip data
ls data # the content

mkdir: data: File exists
bash: line 5: wget: command not found

Archive:  data/names.zip
  inflating: data/names.csv
__init__.py
animacy.tsv
bl_books_sample.csv
input.txt
muse_v3.csv
muse_v3.csv.zip
names.csv
names.zip
names_extract.csv
names_extract.txt
newspapers-toy.csv
tale_beginning.txt

In [14]:
# let load the pandas library as pd again
import pandas as pd
df = pd.read_csv('data/names.csv') # load the csv file as a DataFrame

In [15]:
df.index # row index, index is a list of numbers

RangeIndex(start=0, stop=1858436, step=1)

In [16]:
df.columns # column index, index is a list of names

Index(['year', 'name', 'sex', 'frequency'], dtype='object')

# 2 Retrieving data column-wise

In the code cell below we get the full `'name'` column.

In [4]:
# a simple way to retrieve a column
df['name']

0               Mary
1               Anna
2               Emma
3          Elizabeth
4             Minnie
             ...
1858431       Zykell
1858432       Zyking
1858433        Zykir
1858434        Zyrus
1858435         Zyus
Name: name, Length: 1858436, dtype: object

As an aside, both rows and columns are instances of the `Series` class.

In [5]:
type(df['name'])

pandas.core.series.Series

### ✏️ 1.  Exercise:

- Select the `year` column in `df`.

In [ ]:
# write answer here

You can select multiple columns, but you have to pass the column names as a **list**.

In [ ]:
# this won't work
df['name','sex']

In [ ]:
# this will work
df[['name','sex']]

### ✏️  2. Exercise:

- Select the "track" and "artist" column from `df_muse`.

In [ ]:
# df_muse

## 3 Inspecting columns

What information do these columns contain? Pandas provides you with multiple methods for **understanding** and **transforming** the content of a dataframe.

`.unique()` lists all the unique values in a column. It is useful for getting a sense of the (range of) possible values.

In [ ]:
df['sex'].unique()

`.value_counts()` returns the frequency of each unique value in a column. Below, we count the name of 'male' and 'female' rows.

Be careful with interpretation here! Does this mean there are fewer female names in this dataframe?

In [ ]:
df['sex'].value_counts()

In [ ]:
df['sex'].value_counts(normalize=True)

In [ ]:
df['sex'].value_counts(normalize=True).plot(kind='bar')

### ✏️ Question:

If we apply `.value_counts()` to the "name" column, what do we see?

In [ ]:
df['name'].value_counts()

In [ ]:
df[df['name']=='Robert']['sex'].value_counts()

In [ ]:
(2016 - 1880) * 2

You can select the top `n` values using normal Python slice notation.

In [ ]:
# select the 10 most recurrent names
df['name'].value_counts()[:10]

### ✏️ 3. Exercise:

- For `df_muse` apply `.value_counts()` to the `"artist"` column. 
- Get the names of the ten most frequently mentioned artists in `df_muse`.
- Plot these results in a bar chart.

In [17]:
# write your answer here
df_muse = pd.read_csv('data/muse_v3.csv') # load the csv file as a DataFrame

### ✏️ 4. Exercise:

- How many different genres are there in the `df_muse` dataframe?
- What are the ten most (and least) popular (i.e. frequent) genres?

In [ ]:
# write your answer here

# 4 Retrieving information row-wise

## 4.1 By index 

 `loc` allow you to select data by row and column. The general syntax for `loc` is:
```python
df.loc[row_name, column_name]
```

Similar to lists we can retrieve rows by the index position in the dataframe. We use the same square brackets notation, but precafe it with `.loc`, shorthand for index location.

In [ ]:
df.loc[0]

### ✏️ 5. Exercise:
Get the 11th row in the `df_muse` dataframe.

In [18]:
# write answer here

But Pandas provides more options for retrieving observations by their row index.
Imagine we'd like to access songs by their genre. We have several options at our disposal, but a convenient way would be to set the `genre` column as row index and then retrieve rows based on their genre value (i.e. "rap" or "rock")

In [19]:
# just in case let's load the data again
df_muse = pd.read_csv('data/muse_v3.csv')

In [20]:
df_muse_by_genre = df_muse.set_index('genre') # set the genre column as the index of the dataframe
df_muse_by_genre

,lastfm_url,track,artist,seeds,number_of_emotion_tags,valence_tags,arousal_tags,dominance_tags,mbid,spotify_id
genre,,,,,,,,,,
rap,https://www.last.fm/music/eminem/_/%2527till%2...,'Till I Collapse,Eminem,['aggressive'],6,4.550000,5.273125,5.690625,cab93def-26c5-4fb0-bedd-26ec4c1619e1,4xkOaSrkexMciUUogZKVTS
metal,https://www.last.fm/music/metallica/_/st.%2banger,St. Anger,Metallica,['aggressive'],8,3.710000,5.833000,5.427250,727a2529-7ee8-4860-aef6-7959884895cb,3fOc9x06lKJBhz435mInlH
rap,https://www.last.fm/music/rick%2bross/_/speedi...,Speedin',Rick Ross,['aggressive'],1,3.080000,5.870000,5.490000,NaN,3Y96xd4Ce0J47dcalLrEC8
hip-hop,https://www.last.fm/music/m.i.a./_/bamboo%2bbanga,Bamboo Banga,M.I.A.,"['aggressive', 'fun', 'sexy', 'energetic']",13,6.555071,5.537214,5.691357,99dd2c8c-e7c1-413e-8ea4-4497a00ffa18,6tqFC1DIOphJkCwrjVzPmg
metal,https://www.last.fm/music/dope/_/die%2bmf%2bdie,Die MF Die,Dope,['aggressive'],7,3.771176,5.348235,5.441765,b9eb3484-5e0e-4690-ab5a-ca91937032a5,5bU4KX47KqtDKKaLM4QCzh
...,...,...,...,...,...,...,...,...,...,...
NaN,https://www.last.fm/music/gaby%2bhoffmann%2b%2...,Battle,Gaby Hoffmann & Jay Duplass,['transparent'],1,5.370000,3.450000,5.330000,NaN,NaN
progressive rock,https://www.last.fm/music/omar%2brodriguez-lop...,Hands Tied to the Roots of a Hemorrhage,Omar Rodriguez-Lopez,['transparent'],4,5.797887,4.132254,5.570563,NaN,NaN
NaN,https://www.last.fm/music/ace%2bwhite/_/crookf...,Crookfield Zoo,Ace White,['transparent'],1,5.370000,3.450000,5.330000,NaN,NaN
NaN,https://www.last.fm/music/second%2bchyld/_/tra...,Transparent (Full Version),Second Chyld,['transparent'],1,5.370000,3.450000,5.330000,NaN,NaN
ambient,https://www.last.fm/music/message%2bto%2bbears...,Unfold,Message To Bears,['translucent'],2,3.340000,1.405000,3.500000,247179b0-af1f-4c2b-b4fe-751070d1c0cc,14BYEOeRb3jzglJmKX8eM2

In [21]:
rap_songs = df_muse_by_genre.loc['rap'] # 
rap_songs.shape

(463, 10)

## 4.2 Masking

Another technique for selecting relevant information (which will be often useful) is called **masking**. In this scenario, 
- we define a boolean expression (i.e. one which evaluates to `True` or `False`)
- apply it to a column
- select all rows for which the mask evaluates to `True`.

Below we show how this works for selecting data within a certain date range.

In [22]:
# first we inspect the data type
df.year.dtype

dtype('int64')

In [23]:
# we formulate a boolean expression
year = 1899
print('year > 1900 = ', year > 1900)
print('year < 1900 = ', year < 1900)

year > 1900 =  False
year < 1900 =  True

We can apply this expression to a column, which returns a series with the boolean value for each row index.
This series we use as a **mask** for selecting rows in the dataframe.

In [24]:
df['year'] > 1900

0          False
1          False
2          False
3          False
4          False
           ...
1858431     True
1858432     True
1858433     True
1858434     True
1858435     True
Name: year, Length: 1858436, dtype: bool

In Python `False` is interpreted as zero and `True` as 1. To measure how many rows match a condition we can apply `sum` to a mask.

In [25]:
# we have 1802468 row with names after 1900
sum(df['year'] > 1900)

1802468

In [26]:
# saving subset in a new dataframe
# note that index does not start from zero!
mask = df.year > 1900
df_after_1900 = df[mask]
df_after_1900

         year      name sex  frequency
55968    1901      Mary   F      13136
55969    1901     Helen   F       5247
55970    1901      Anna   F       4923
55971    1901  Margaret   F       4424
55972    1901      Ruth   F       3974
...       ...       ...  ..        ...
1858431  2015    Zykell   M          5
1858432  2015    Zyking   M          5
1858433  2015     Zykir   M          5
1858434  2015     Zyrus   M          5
1858435  2015      Zyus   M          5

[1802468 rows x 4 columns]

In [27]:
sum(df['year'] > 1900) == df_after_1900.shape[0]

True

### ✏️ 6. Exercises:
- What is the output of the code example below?
```python
df['year'].between(1900,1910)
```
- can you adapt the code to select rows between 1950 and 1960 (all names from the fifties)

In [ ]:
# type answer here

### ✏️ 7. Exercises:

- Select all rows in which the value for the variable 'sex' is equal to 'F'. (Google "is equal to" operator Python)
- Save this in a new Python variable called `names_f`
- How many rows does the dataframe `names_f` contain?
- Repeat the same for male baby names. Apply `.describe()` to `names_f` and `names_m`. What differences do you see?

In [ ]:
# type answer here

## 4.3 Finding Information: Count and Select

#### Searching for love, love.

Pandas provides powerful functions to search through text and then select rows based on the number of hits. 

Below we show to:
- use the `count()` method to search for the string 'love' in the track titles
- use a mask to select all songs that mention 'love' at least twice

In [ ]:
# with applying count to a column we can count the number of occurences of a specific string
df_muse['track'].str.count('love')

In [ ]:
# we can also count the number of occurences of a specific string in a case-insensitive way
df_muse['track'].str.lower().str.count('love')

In [ ]:
# we cas save the result (search ignoring capitalization) in a new column
df_muse['hits'] = df_muse['track'].str.lower().str.count('love')

In [ ]:
# we can create a mask to filter the rows with more than one occurence of the word 'love'
mask = df_muse['hits'] > 1
mask

In [ ]:
# we can apply the mask to the dataframe
df_muse[mask]

## 4.4 Combining conditions

In [ ]:
# endless options
# for example all female names between 1940 and 1945
df[(df.year.between(1940,1945)) & (df.sex=='F')]